apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: install-tools
        image: alpine:latest
        command: ["sh", "-c", "apk add --no-cache apache2-utils && htpasswd -bc /tmp/.htpasswd user1 password1"]
        volumeMounts:
        - name: htpasswd-volume
          mountPath: /tmp
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: htpasswd-volume
          mountPath: /etc/nginx/.htpasswd
          subPath: .htpasswd
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: htpasswd-volume
        emptyDir: {}
